import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { Toaster } from 'react-hot-toast';
import { GlobalProvider } from '@/context/GlobalState';
import { useState } from 'react';
export default function Home() {
  const [authOption, setAuthOption] = useState<string>('Login');
  const [landingDate, setLandingDate] = useState<Date>(new Date());
  return (
    <>
      <GlobalProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              fontSize: '1.8rem',
            },
          }}
        />

        <Link href="/landing" />

        <Link href="/auth" />

        <Link href="/main" />
      </GlobalProvider>
    </>
  );
}
